function assets = universe()
%UNIVERSE Cross-asset universe metadata. Only Binance crypto rows are live in V1.
    assets = table( ...
        ["BTCUSDT"; "ETHUSDT"; "SOLUSDT"; "USDT"; "SPY"; "QQQ"; "GLD"; "000300.SH"; "000001.SH"], ...
        ["BTC"; "ETH"; "SOL"; "USDT"; "S&P 500 ETF"; "Nasdaq 100 ETF"; "Gold ETF"; "CSI 300"; "SSE Composite"], ...
        ["Crypto"; "Crypto"; "Crypto"; "Cash"; "US Equity"; "US Equity"; "Commodity"; "China Equity"; "China Equity"], ...
        ["Binance"; "Binance"; "Binance"; "Synthetic"; "Stooq"; "Stooq"; "Stooq"; "FutureAdapter"; "FutureAdapter"], ...
        [true; true; true; true; false; false; false; false; false], ...
        'VariableNames', {'Symbol', 'Name', 'AssetClass', 'DataSource', 'IsLive'});
end
